### PR TITLE
Major bug fixes and slight improvements

### LINKED ISSUE #81: Adding tooltips to buttons
**Description**
Adding tooltips to  floating action button and icon buttons in action bar

**Additional context**
Most of the icons like floating action button and icons in action bar of different screen have no tooltip. Tooltip will help guess the functionality of button (which is not possible just by looking at the icon). When you hold the icon a little tooltip with name of button pops up (if added).

### LINKED ISSUE #82: Messages not showing up just after creating a group
Just after a group is created, the messages section doesn't show up the messages. Error is thrown by the future builder.

Other members working are
@kshitijalwadhi 
@Ishaan21

### LINKED ISSUE #83: Leave group button can be pressed multiple times
There is a delay between pressing leave group button and navigating to dashboard. During that period, the leave group button can be pressed multiple times leading to negative number of people in group

Other members working are
@kshitijalwadhi

### PR DESCRIPTION
**Pull request by kshitijalwadhi**
* Fixed a major message screen bug #82 
* Fixed leave group button bug #83 
* Added tooltip #81 
* Fixed color schemes in auth screens
* Updated destinations to include more destinations, also accounted for the change in icons.

Fixed #82, fixed #83, fixed #81

### CODE REVIEW

File: lib/screens/groupscreen/group.dart [hunk 1]
```diff
@@ -71,20 +73,29 @@ class _GroupPageState extends State<GroupPage> with AutomaticKeepAliveClientMixi
...
+                          }
+                        },
+                        label: Text('Leave Group'),
+                      )
+                    : FlatButton.icon(
+                        textColor: getVisibleColorOnPrimaryColor(context),
+                        icon: Icon(FontAwesomeIcons.signOutAlt),
+                        onPressed: null,
+                        label: Text('Leave Group'),
+                      )
```
Comment (tmibvishal) [inline lib/screens/groupscreen/group.dart:98]: So this buttonEnabled is added so that user doesn't click on leave group rapidly 2 times ?
} catch (e) {
print(e.toString());
} if it fails. Then reenable the button
You can ignore set state here by having a code like this

```dart
appBar: AppBar(
              title: Text('Group Details'),
              actions: <Widget>[
                FlatButton.icon(
                  textColor: getVisibleColorOnPrimaryColor(context),
                  icon: Icon(FontAwesomeIcons.signOutAlt),
                  onPressed: () async {
                    if (buttonEnabled) {
                      try {
                        buttonEnabled = false;
                        await _request.exitGroup();
                        Navigator.pop(context);
                      } catch (e) {
                        buttonEnabled = true;
                        print(e.toString());
                      }
                    }
                  },
                  label: Text('Leave Group'),
                )
              ],
            ),
```
